name: "Sphinx: Render docs"

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install \
            sphinx \
            myst-parser \
            sphinxcontrib-autodoc-pydantic \
            sphinx-inline-tabs \
            sphinx-design \
            sphinx-copybutton \
            sphinxcontrib-mermaid \
            sphinx-search-extension

      - name: Build HTML
        run: sphinx-build -b html source source/build/html

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: html-docs
          path: source/build/html/

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: source/build/html/
